### ISSUE TITLE
[EMU] EQ crashing after a while when zoning

### ISSUE THREAD

**Issue by intered** [macroquest/macroquest#668] opened 2022-11-23 16:11 UTC
Hey guys, I am running 18 toons on a EMU server and using the RG MQ build (version 22-11-2022 06:44:14). The client is stable for the first half hour or so, after that, toons keep crashing while zoning.

What Ive tried myself:

1. Fresh installation of EQ and MQ
2. Formatted HD and re-installed windows and EQ/MQ
3. Changed RAM from 40gb to 2x16GB
4. replaced 2x16GB to 2x32GB
5. Tried different eqclient.ini (if that even has some effect on it)

But still, the client keep crashing. I was on the RoF2 MQ client before, and had some crashes also (since 32bit is also not that stable) - but not nearly as much as I do have now with the RG MQ build.

Attached is a dumb file and a log from MQ

[dump-log.zip](https://github.com/macroquest/macroquest/files/10077212/dump-log.zip)
<img width="295" alt="screenshot" src="https://user-images.githubusercontent.com/16416072/203594756-a2a997b0-69fc-4e4a-bf70-12d19348fc3f.png">
<img width="236" alt="screenshot2" src="https://user-images.githubusercontent.com/16416072/203594761-daa02e45-0504-42c8-ada3-1e9273f94532.png">

**Comment by brainiac** [comment] 2022-11-25 07:47
duplicate of #659

**Closed by brainiac** 2022-11-25 07:47 UTC
Labels: emu
