### ISSUE TITLE
[BUG] ImGui.TableSetBgColor not working.

### ISSUE THREAD

**Issue by martinb-uk** [macroquest/macroquest#818] opened 2024-01-20 23:56 UTC
**Describe the bug**
It appears that since the Jan 17th patch it is not possible to set Row/Cell background colours using ImGui. 
ImGui.TableSetBgColor(ImGuiTableBgTarget.CellBg, ... )
ImGui.TableSetBgColor(ImGuiTableBgTarget.RowBg0, ... )
ImGui.TableSetBgColor(ImGuiTableBgTarget.RowBg1, ... )
all appear to have the same problem.

**To Reproduce**
`/lua run examples/imgui_demo`

See screenshot below of where the backgrounds should be coloured.

**Expected behavior**
Row + Cell background colours to work, as they did before the patch.

**Screenshots**

![image](https://github.com/macroquest/macroquest/assets/19375324/721b7c5b-d024-415e-b943-150388298ef8)

**MQ Version**
- [X] Live
- [ ] Test
- [ ] Emu (ROF2)

**Comment by brainiac** [comment] 2024-01-21 00:26
it works, the demo just had an off-by-one error

**Comment by martinb-uk** [comment] 2024-01-21 01:12
Its definitely working for you? Some code I had working before was no longer working, and a simple recreate, which I think should work, is also not working for me.

`local ImGui = require('ImGui')
local mq = require('mq')

local gui = {
    open = true,
    draw = true
}

local function Render()
    if not gui.open then return end
    local flags = bit32.bor(ImGuiWindowFlags.NoFocusOnAppearing,ImGuiWindowFlags.AlwaysAutoResize)

    gui.open, gui.draw = ImGui.Begin("-- Bug? --", gui.open, flags)
    if gui.draw and gui.open then
        if ImGui.GetWindowHeight() == 32 and ImGui.GetWindowWidth() == 32 then
            ImGui.SetWindowSize(460, 177)
        end
        local flags = bit32.bor(ImGuiTableFlags.RowBg, ImGuiTableFlags.BordersOuter, ImGuiTableFlags.BordersV, ImGuiTableFlags.ScrollY,ImGuiTableFlags.Resizable)
        if ImGui.BeginTable("ATable", 2, flags, 0, 0, 0.0) then
            ImGui.TableSetupColumn('Property', ImGuiTableColumnFlags.WidthFixed,   -1.0, 1)
            ImGui.TableSetupColumn('Value',    ImGuiTableColumnFlags.WidthStretch,  -1.0, 2)
            ImGui.TableSetupScrollFreeze(0, 1)
            ImGui.TableHeadersRow()
            for i=1,3 do
                ImGui.TableNextRow()
                ImGui.TableNextColumn()
                ImGui.Text("aProp")
                ImGui.TableNextColumn()
                ImGui.TableSetBgColor(ImGuiTableBgTarget.CellBg, 0.1, 0.1, 0.7, 0.65)
                ImGui.Text("aValue")
            end
            ImGui.EndTable()
        end
    end
    ImGui.End()
end

function gui.Init()
    mq.imgui.init('cell-bg-bug', Render)
end

return gui`


![image](https://github.com/macroquest/macroquest/assets/19375324/a5c25cd2-4d33-49e1-a875-20b630d1d4aa)

**Comment by brainiac** [comment] 2024-01-21 01:22
![image](https://github.com/macroquest/macroquest/assets/57729/f1a3140d-e045-41d6-baf3-435678e82def)

🤷🏼

**Comment by martinb-uk** [comment] 2024-01-21 01:27
Interesting - thanks. Its happening consistently for me across a number of machines but I will try and track down the root cause.

**Comment by brainiac** [comment] 2024-01-21 01:51
debug build works fine, release is where the issue is at. looking into it.

**Comment by brainiac** [comment] 2024-01-21 02:12
ok this time should be fixed.

**Closed by brainiac** 2024-01-21 02:12 UTC
Labels: bug
